### ISSUE TITLE
"react-scripts-typescript-scss" is deprecated

### ISSUE THREAD

**Issue by evkhramkov** [bidmachine/BidMachine-Dashboard#1]
Hello!

I would strongly recommend to remove that dependency and use official [`react-scripts`](https://www.npmjs.com/package/react-scripts) package, because `react-scripts-typescript-scss` is very outdated and not maintained anymore.

Potentially `react-scripts` should work with TypeScript and SCSS out of the box:
https://facebook.github.io/create-react-app/docs/adding-typescript
https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet

https://github.com/bidmachine/BidMachine-Dashboard/blob/dee94baf09c1ea0527c7864787a5d41ae919a45b/package.json#L31

**Comment by jpascal** [comment]
@evkhramkov Thank for recommendations.
